# Generated by Django 2.0.2 on 2018-03-05 04:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(default='', max_length=64, unique=True, verbose_name='Nombre')),
                ('Representante', models.CharField(default='', max_length=64, verbose_name='Representante')),
                ('Telefono', models.CharField(default='', max_length=17, validators=[django.core.validators.RegexValidator(message="El numero de telefono debe estar en este formato: '+999999999'. Con 15 digitos maximos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefono')),
                ('Correo', models.EmailField(default='', max_length=128, verbose_name='Correo Electronico')),
                ('Logo', models.ImageField(default='', upload_to='media/equipo', verbose_name='Foto')),
                ('ColorVisitante', models.CharField(default='', max_length=7, verbose_name='Color de Visitante')),
                ('ColorLocal', models.CharField(default='', max_length=7, verbose_name='Color de Local')),
                ('Cancha', models.CharField(default='', max_length=128, verbose_name='Cancha del Equipo')),
                ('Dia', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')], default=1)),
                ('Hora', models.TimeField()),
            ],
        ),
    ]
