# Generated by Django 2.0.2 on 2018-03-02 16:43

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('Apellido', models.CharField(default='', max_length=50, verbose_name='Apellido')),
                ('Nacimiento', models.DateField(default='', verbose_name='Fecha de Nacimiento')),
                ('Numero', models.IntegerField(default='', verbose_name='Número')),
                ('Posicion', models.IntegerField(default='', verbose_name='Posición')),
                ('Notas', models.TextField(default='', max_length=150, verbose_name='Comentarios')),
                ('Imagen', sorl.thumbnail.fields.ImageField(default='', upload_to='media/jugadora', verbose_name='Foto')),
            ],
        ),
    ]
