# Generated by Django 2.0.2 on 2018-03-05 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('Apellido', models.CharField(default='', max_length=50, verbose_name='Apellido')),
                ('Nacimiento', models.DateField(default='', verbose_name='Fecha de Nacimiento')),
                ('Numero', models.IntegerField(default='', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número')),
                ('Posicion', models.IntegerField(choices=[(1, 'Delantero'), (2, 'Medio'), (3, 'Defensa'), (4, 'Portero')], default='', verbose_name='Posición')),
                ('Notas', models.TextField(blank=True, default='', max_length=150, null=True, verbose_name='Comentarios')),
                ('Imagen', models.ImageField(blank=True, default='', null=True, upload_to='jugadora', verbose_name='Foto')),
            ],
        ),
    ]
